name: "aliyundriver_auto_checkin"

on:
  schedule:
    - cron: "0 23 * * *"  
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-300 -n 1)

      - name: Install dependencies
        run: |
          npm install

      - name: Run checkin
        env:
          refreshToken: ${{ secrets.refreshToken }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: |
          node ./main.js
